spring:
  main:
    allow-bean-definition-overriding: true
dialob:
  session:
    postSubmitHandler:
      enabled: false
    rest:
      cors:
        default:
          allowedOrigins:
            - "http://localhost:3000"
            - "http://localhost:3001"
            - "http://localhost:8081"
            - "http://localhost:8083"
            - "http://localhost:8085"
          allowedMethods:
            - POST
            - PUT
            - OPTIONS
            - GET
          allowedHeaders:
            - "*"
          allowCredentials: true
