spring:
  # docker run --name dialob-postgres -p 5432:5432 -e POSTGRES_PASSWORD=password123 postgres
  datasource:
    username: postgres
    password: password123
    url: jdbc:postgresql://localhost/postgres
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/migration_{vendor}

dialob.db:
  database-type: JDBC
#   jdbc.schema: dialob

admin.versioning: true
