login.server.url: "https://login.example.com"

dialob:
  security:
    enabled: true

spring:
  security:
    oauth2:
      client:
        registration:
          default:
            provider: "oauth2-login-provider"
            clientName: default
            clientId: localhost
            clientSecret: mysecret
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid   # We'll only get "idToken" (SSO)
              - profile  # Triggers userinfo lookup from "userInfoUri"
        provider:
          oauth2-login-provider:
            authorizationUri: ${login.server.url}/oauth/authorize
            tokenUri: ${login.server.url}/oauth/token
            jwkSetUri: ${login.server.url}/token_keys
            userNameAttribute: sub
            userInfoUri: ${login.server.url}/userinfo
