spring:
  data:
    gcdatastore:
      repositories:
        enabled: true # Enable Google cloud repositories.
      database: "${dialob.tenant.fixedId:}dialob"
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
dialob.db:
  database-type: GCDATASTORE
