spring:

server:
  port: 8081
  use-forward-headers: true
  servlet:
    context-path: "/"
    session.timeout: 7200
  error:
    include-stacktrace: always
    

host: "http://localhost:${server.port}"

management:
  server:
    servlet.context-path: "/manage"
    add-application-context-header: false
      

# disable all configurations 
dialob.enabled: true

#
dialob.composer.ui.enabled: true
dialob.composer.ui.redirect: false
dialob.composer.ui.https: false 
dialob.composer.ui.oidc-path:  ''
dialob.composer.ui.status-path: ''
dialob.composer.ui.service-path: /ide

dialob.composer.service.enabled: true
dialob.composer.service.service-path: /assets

# form releated db enabled, default path classpath*:assets/
dialob.formdb.inmemory.enabled: false
dialob.formdb.inmemory.path: classpath*:assets/

#form db config - local file storage
dialob.formdb.file.enabled: false
dialob.formdb.file.path: src/main/resources
dialob.formdb.file.email: asset.manager@resys.io

#form db config - postgresql storage
dialob.formdb.pg.enabled: false
dialob.formdb.pg.autoCreate: true
dialob.formdb.pg.repositoryName: "dialob-repo-1" 
dialob.formdb.pg.branchSpecifier: "main"
dialob.formdb.pg.pgHost: "localhost"
dialob.formdb.pg.pgDb: "postgres"
dialob.formdb.pg.pgUser: "postgres"
dialob.formdb.pg.pgPass: "example"


