const en = {
  'locales.en': 'English',
  'locales.fi': 'Finnish',
  'locales.sv': 'Swedish',
  'locales.et': 'Estonian',

  'translations': 'Translations',
  'variables': 'Variables',
  'lists': 'Lists',
  'options': 'Options',
  'version': 'Version',
  'version.latest': 'LATEST',
  'search': 'Search',
  'preview': 'Preview',

  'page.label': 'Page label',

  'buttons.visibility': 'Visibility',
  'buttons.cancel': 'Cancel',
  'buttons.confirm': 'Confirm',

  'menus.options': 'Options',
  'menus.change.id': 'Change ID',
  'menus.delete': 'Delete',
  'menus.duplicate': 'Duplicate',
  'menus.conversions.hint': 'Convert to:',
  'menus.add': 'Add item',
  'menus.insert.below': 'Insert below',

  'placeholders.group': 'Group label',
  'placeholders.surveygroup': 'Survey group label',
  'placeholders.rowgroup': 'Multi-row group label',
  'placeholders.survey': 'Survey field label',
  'placeholders.address': 'Address field label',
  'placeholders.text': 'Text field label',
  'placeholders.time': 'Time field label',
  'placeholders.date': 'Date field label',
  'placeholders.number': 'Number field label',
  'placeholders.decimal': 'Decimal field label',
  'placeholders.boolean': 'Boolean field label',
  'placeholders.list': 'List field label',
  'placeholders.multichoice': 'Multi-choice field label',
  'placeholders.validation': 'Validation message text',
  'placeholders.note': 'Note text',

  'dialogs.confirmation.delete.title': 'Delete item',
  'dialogs.confirmation.delete.text': 'Are you sure you want to delete {itemId}?',
  'dialogs.confirmation.duplicate.title': 'Duplicate item',
  'dialogs.confirmation.duplicate.text': 'Are you sure you want to duplicate {itemId}?',

  'errors.type.VARIABLE': 'Variable',
  'errors.type.VISIBILITY': 'Visibility',
  'errors.type.DEFAULT_VALUE': 'Default value',
  'errors.type.REQUIREMENT': 'Requirement',
  'errors.type.VALIDATION': 'Validation',
  'errors.type.VALUESET': 'List',
  'errors.type.VALUESET_ENTRY': 'List entry',
  'errors.type.CANADDROW': 'Add row',
  'errors.type.CANREMOVEROW': 'Remove row',
  
  'errors.message.RB_VARIABLE_NEEDS_EXPRESSION': 'Missing expression',
  'errors.message.INVALID_DEFAULT_VALUE': 'Invalid value',
  'errors.message.UNKNOWN_VARIABLE': 'Unknown variable',
  'errors.message.SYNTAX_ERROR': 'Syntax error',
  'errors.message.COULD_NOT_DEDUCE_TYPE': 'Can\'t deduce type ',
  'errors.message.NO_ORDER_RELATION_BETWEEN_TYPES': 'Can\'t compare these variables',
  'errors.message.NO_EQUALITY_RELATION_BETWEEN_TYPES': 'Can\'t compare these variables',
  'errors.message.BOOLEAN_EXPRESSION_EXPECTED': 'Boolean expression expected',
  'errors.message.VALUESET_EMPTY': 'Choice list is empty',
  'errors.message.VALUESET_DUPLICATE_KEY': `Choice list has duplicate key "{expression}"`,
  'errors.message.VALUESET_EMPTY_KEY': 'Choice list has empty key',
  'errors.message.CONTEXT_VARIABLE_UNDEFINED_TYPE': 'Context variable type not defined',
  'errors.message.VALUE_TYPE_NOT_SET': 'Value type not set',
  'errors.message.TAG_EXISTS': 'Tag already exists',
  'errors.message.MATCHER_REGEX_SYNTAX_ERROR': 'Invalid regular expression',
  'errors.message.MATCHER_DYNAMIC_REGEX': 'Dynamic regular expressions not supported',
  'errors.message.REDUCER_TARGET_MUST_BE_REFERENCE': 'Multirow aggregate function target must be directly multirow item',
  'errors.message.CANNOT_USE_REDUCER_INSIDE_SCOPE': 'Multirow aggregate function can\'t be used for non-multirow item',
  'errors.message.UNKNOWN_REDUCER_OPERATOR': 'Unknown multirow aggregate function',
  'errors.message.OPERATOR_CANNOT_REDUCE_TYPE': 'This aggregate function can\'t be used for this item type',
  'errors.message.UNKNOWN_FUNCTION': 'Undefined function',

};

export default en;
