nodeId: "default"

server:
  port: 8080
  use-forward-headers: true
  servlet:
    contextPath: "/session"

management:
  endpoints:
    web:
      base-path: "/manage"
      exposure:
        include: '*'

host: "http://localhost:${server.port}"

spring:
  aop:
    proxy-target-class: false
  application:
    name: ${project.artifactId:}
  profiles:
    active:
    - jdbc
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    deserialization:
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  cloud:
    gcp:
      core:
        enabled: false
      pubsub:
        enabled: false

info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    version: "@project.version@"
    timestamp: "@timestamp@"
    number: "@buildNumber@"

logging:
  path: "./"


endpoints.jmx.staticNames: 'application=session'

dialob:
  security:
    audit:
      enabled: false
  session:
    security:
      # Only AWS supported
      enabled: false
    cache:
      type: LOCAL
    autosave:
      enabled: false
      interval: 5000
    rest:
      enabled: true
      context: "/dialob"
      cors:
#        default:
#          allowedOrigins:
#            - "*"
#          allowedMethods:
#            - PUT
#            - OPTIONS
#          allowedHeaders:
#            - content-type
#          exposedHeaders:
#            - content-type
#          allowCredentials: false
#        00000000-0000-0000-0000-000000000000:
#          allowedOrigins:
#            - "https://client.com"
#            - "http://localhost:3000"
        "5ed37622-72cf-4729-9a72-5a30473a61ef":
          allowedMethods:
            - GET
            - OPTIONS
            - POST
            - PUT
            - HEAD
          allowedHeaders:
            - content-type
          allowedOrigins:
            - "http://localhost:8081"
          allowCredentials: true
    sockjs:
      enabled: true
      webSocketEnabled: true
      contextPath: "/socket"
      urlAttributes:
        sessionId: sessionId
        tenantId: tenantId
      libraryUrl: "//cdn.jsdelivr.net/sockjs/1/sockjs.min.js" # "/static/js/sockjs-client.js"
      maxTextMessageBufferSize: 131072
      maxBinaryMessageBufferSize: 131072
      sendTimeLimit: 5000
      allowedOrigins:
        - "*"


