server:
  max-http-request-header-size: 64KB
  port: 8081
  use-forward-headers: true
  servlet:
    contextPath: ""
    error:
      # never, on_trace_param ( url -> ?trace=true ), always
      include-stacktrace: always

spring:
  autoconfigure:
    exclude:
    - "org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration"
    - "org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration"
    - "org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration"
  profiles:
    active:
    - jdbc
    - ui
  aop:
    proxy-target-class: false
  session:
    store-type: none
  application:
    name: ${project.artifactId:dialob-boot}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    deserialization:
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  cloud:
    gcp:
      core:
        enabled: false
      pubsub:
        enabled: false

info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    version: "@project.version@"
    timestamp: "@timestamp@"
    number: "@buildNumber@"

logging:
  path: "./"

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

dialob:
  api:
    context-path: "/api"
    apiKeySalt: "secret"
    apiKeys:
    - tenantId: "${dialob.tenant.fixedId:00000000-0000-0000-0000-000000000000}"
      clientId: "${dialob.tenant.fixedId:00000000-0000-0000-0000-000000000000}"
      # hmacsha256 hash of "localsecret" and key secret "secret"
      hash: "kG0621+jXaUCcPpBJIluHXjlA//sWO3zGaq5BAuq+lQ="

    schemes:
    - type: apiKey
      name: ApiKey
      keyName: "x-api-key"
      passAs: "header"
    cors:
      allow-credentials: true
      allowed-headers:
      allowed-methods:
        - GET
        - HEAD
        - POST
        - PUT
      allowed-origins:
        - "*"
      exposed-headers:
      max-age: 1800s
  security:
    enabled: false
    audit:
      enabled: false
    groupPermissions:
      "dialob.questionnaire.view":
        - questionnaires.get
      "dialob.questionnaire.edit":
        - questionnaires.put
        - questionnaires.post
      "dialob.questionnaire.delete":
        - questionnaires.delete
      "dialob.form.view":
        - forms.get
      "dialob.form.edit":
        - forms.put
        - forms.post
        - forms.delete
      "dialob.audit":
        - audit
      "dialob.admin":
        - tenant.all
      "dialob.composer":
        - composer.view
        - manager.view
  session:
    cache:
      type: NONE
