
cdn: "https://cdn.resys.io"  # CDN backend storage storage access. Instant updates
documentationUrl: "https://docs.dialob.io"

global:
  view:
    reactHook: true
    logo:
      url: "https://cdn.resys.io/dialob_logo.svg"
      width: 180
      height: 40
      title: ""

admin:
  version: dev
  context-path: "/"
  versioning: false
  apiUrl: '${server.servlet.contextPath}/api'
  fillingAppUrl: "${server.servlet.contextPath}/fill"
  reviewAppUrl: "${server.servlet.contextPath}/review"
  composerAppUrl: "${server.servlet.contextPath}/composer"
  documentation: "${documentationUrl}"
  tenants:
    default:
      template: "https://cdn.resys.io/dialob/demo-dialob-io-app/${admin.version}/index.html"

landing:
  context-path: "/landing"
  apiUrl: '${server.servlet.contextPath}/api'
  fillingAppUrl: "${server.servlet.contextPath}/fill"
  composerAppUrl: "${server.servlet.contextPath}/composer"
  adminAppUrl: "${server.servlet.contextPath}/"
  tenants:
    default:
      template: "landing"
      attributes:
        javascriptFiles:
          - "//cdn.polyfill.io/v2/polyfill.min.js"
          - "//unpkg.com/react@16.0.0/umd/react.development.js"
          - "//unpkg.com/react-dom@16.0.0/umd/react-dom.development.js"
        stylesheets:
          - ""

questionnaire:
  version: dev
  context-path: "/fill"
  socketUrl: "${server.servlet.contextPath}/session/socket"
  restUrl: "${server.servlet.contextPath}/session/dialob"
  backendApiUrl: "${server.servlet.contextPath}/api"
  reviewUrl: "${server.servlet.contextPath}/review"
  connectionMode: "rest"
  tenants:
    default:
      template: "https://cdn.resys.io/dialob/dialob-fill-demo-material/${questionnaire.version}/index.html"

composer:
  version: dev
  subApplicationName: Composer
  context-path: "/composer"
  fillingAppUrl: "${server.servlet.contextPath}/fill"
  backendApiUrl: "${server.servlet.contextPath}/api"
  adminAppUrl: "${server.servlet.contextPath}/"
  documentationUrl: "${documentationUrl}"
  tenants:
    default:
      template: "https://cdn.resys.io/dialob/composer-material/${composer.version}/index.html"

review:
  version: dev
  subApplicationName: Review
  context-path: "/review"
  apiUrl: "${server.servlet.contextPath}/api"
  tenants:
    default:
      template: "https://cdn.resys.io/dialob/review-material/${review.version}/index.html"

springdoc:
#  swagger-ui:
#    path: "/v3/swagger-ui.html"
  api-docs:
    enabled: true
