
cdn: "https://cdn.resys.io"  # CDN backend storage storage access. Instant updates
documentationUrl: "https://docs.dialob.io"

global:
  view:
    reactHook: true
    logo:
      url: "https://cdn.resys.io/dialob_logo.svg"
      width: 180
      height: 40
      title: ""

admin:
  context-path: "/"
  versioning: false
  apiUrl: '${server.servlet.contextPath}/api'
  fillingAppUrl: "${server.servlet.contextPath}/fill"
  reviewAppUrl: "${server.servlet.contextPath}/review"
  composerAppUrl: "${server.servlet.contextPath}/composer"
  documentation: "${documentationUrl}"
  tenants:
    default:
      template: "admin"
      attributes:
        frontendPath: "https://cdn.resys.io/dialob/dialob-admin-ui/master/"
        javascriptFiles:
          - "//cdn.polyfill.io/v2/polyfill.min.js"
        stylesheets:
          - "${server.servlet.contextPath}/css/layout.css"
          - "//unpkg.com/semantic-ui@2.4.2/dist/semantic.min.css"

landing:
  context-path: "/landing"
  apiUrl: '${server.servlet.contextPath}/api'
  fillingAppUrl: "${server.servlet.contextPath}/fill"
  composerAppUrl: "${server.servlet.contextPath}/composer"
  adminAppUrl: "${server.servlet.contextPath}/"
  tenants:
    default:
      template: "landing"
      attributes:
        javascriptFiles:
          - "//cdn.polyfill.io/v2/polyfill.min.js"
          - "//unpkg.com/react@16.0.0/umd/react.development.js"
          - "//unpkg.com/react-dom@16.0.0/umd/react-dom.development.js"
        stylesheets:
          - ""

questionnaire:
  version: master
  context-path: "/fill"
  socketUrl: "${server.servlet.contextPath}/session/socket"
  restUrl: "${server.servlet.contextPath}/session/dialob"
  backendApiUrl: "${server.servlet.contextPath}/api"
  reviewUrl: "${server.servlet.contextPath}/review"
  connectionMode: "rest"
  tenants:
    default:
      template: "fill"
      attributes:
        javascriptFiles:
          - "//cdn.resys.io/dialob-fill-ui-app/${questionnaire.version}/runtime.js"
          - "//cdn.resys.io/dialob-fill-ui-app/${questionnaire.version}/app.js"
        stylesheets:
          - "//cdn.resys.io/dialob-fill-ui-app/${questionnaire.version}/app.css"
          - "//unpkg.com/semantic-ui@2.4.1/dist/semantic.min.css"


composer:
  version: master
  context-path: "/composer"
  fillingAppUrl: "${server.servlet.contextPath}/fill"
  backendApiUrl: "${server.servlet.contextPath}/api"
  adminAppUrl: "${server.servlet.contextPath}/"
  subApplicationName: Composer
  documentationUrl: "${documentationUrl}"
  tenants:
    default:
      template: "//cdn.resys.io/dialob-composer-generic-app/dev/index.html"

review:
  context-path: "/review"
  apiUrl: "${server.servlet.contextPath}/api"
  subApplicationName: Review
  tenants:
    default:
      template: "review"
      attributes:
        frontendPath: "https://cdn.resys.io/dialob/dialob-review-ui-app/master/"
        stylesheets:
          - "//unpkg.com/semantic-ui@2.4.2/dist/semantic.min.css"

springdoc:
#  swagger-ui:
#    path: "/v3/swagger-ui.html"
  api-docs:
    enabled: true
