on:
  push:
    paths:
      - 'api/**'
    branches:
      - main

name: main - release - java 17
jobs:
  build:
    name: Releasing API from branch - main
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        cache: 'maven'
        distribution: 'corretto'
        gpg-private-key: ${{ secrets.DIALOB_GPG_KEY }}
        gpg-passphrase: DIALOB_GPG_SEC
        server-id: oss.sonatype.org
        server-username: OSSRH_USER
        server-password: OSSRH_PASS

    - name: tag - release api - upload
      shell: bash
      run: ./dialob-api-build-parent/release.sh
      env:
        BOT_NAME: "info"
        BOT_EMAIL: "info@dialob.io"
        DIALOB_GPG_SEC: ${{ secrets.DIALOB_GPG_SEC }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        OSSRH_PASS: ${{ secrets.OSSRH_PASS }}

