on:
  push:
    branches:
      - dev

name: main - release - java 11
jobs:
  build:
    name: Build - dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          ref: ${{ github.event.ref }}
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: tag - upload
        run: ./dialob-build-parent/build.sh
        env:
          CI: false


