on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'frontends/**'
      - 'utils/**'
      - '**/*.md'
      - 'compose/**'
      - 'dev-env/**'
      - 'api/**'
    branches:
      - dev

name: dev - build - deploy

jobs:
  build:
    name: Build - dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Docker Registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_SNAPSHOT_REGISTRY }}
          username: ${{ vars.DOCKER_SNAPSHOT_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_SNAPSHOT_REGISTRY_TOKEN }}

      - name: tag - upload
        run: ./dialob-build-parent/build.sh
        env:
          CI: true
          DOCKER_REGISTRY: ${{ vars.DOCKER_SNAPSHOT_REGISTRY }}
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: upload image metadata
        uses: actions/upload-artifact@v4
        with:
          name: jib-image
          path: '**/target/jib-image.*'
