on:
  push:
    branches:
      - dev-2.1

name: dev-2.1 - build - deploy

jobs:
  build:
    name: Build - dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'maven'

      - name: Docker Registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_SNAPSHOT_REGISTRY }}
          username: ${{ vars.DOCKER_SNAPSHOT_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_SNAPSHOT_REGISTRY_TOKEN }}

      - name: tag - upload
        run: ./dialob-build-parent/build.sh
        env:
          CI: false
          DOCKER_REGISTRY: ${{ vars.DOCKER_SNAPSHOT_REGISTRY }}


