on:
  push:
    tags:
      - '2.**'

name: docker - build - deploy

jobs:
  build:
    name: Dockerizing - main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          ref: ${{ env.GITHUB_REF_NAME }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: tag - release - upload - docker
        run: ./dialob-build-parent/docker.sh
        env:
          GITHUB_SHA: ${GITHUB_SHA}
          GITHUB_REF: ${GITHUB_REF}
          GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
        
