on:
  push:
    paths:
      - 'dialob-docusaurus/**'
    branches:
      - dev
      - main

  workflow_dispatch:

name: Docusaurus - Build - Documentation

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    outputs:
      documentation: ${{ steps.distribution-packages.outputs.documentation }}
    defaults:
      run:
        working-directory: dialob-docusaurus
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: dialob-docusaurus/package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Upload build artifact
        id: distribution-packages
        uses: actions/upload-artifact@v7
        with:
          name: documentation
          path: dialob-docusaurus/build

  publish:
    name: Publish documentation
    permissions:
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.ASSUME_ROLE }}
        role-session-name: DialobDocusaurusBuild

    - name: Download documentation artifact
      id: download
      uses: actions/download-artifact@v8
      with:
        name: 'documentation'
        path: ${{ github.workspace }}/artifacts

    - name: Publish documentation to S3
      run: |
        if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
          EXPIRY_DATE=`date -I -d '30 days'`
          echo "Pull request's upload expires on $EXPIRY_DATE"
          EXPIRES="--expires $EXPIRY_DATE"
        fi
        for PROJECT in `ls -1 $DOWNLOAD_PATH`; do
          mkdir temp
          tar -C temp -xzvf $DOWNLOAD_PATH/$PROJECT
          cd temp
          CONTEXT=`find . -mindepth 2 -maxdepth 2 -type d`
          TARGET=s3://${{ secrets.DOCUMENTATION_BUCKET }}/${CONTEXT#"./"}
          aws s3 sync $EXPIRES --acl public-read --delete --cache-control public,max-age=3600 $CONTEXT $TARGET
          cd ..
          rm -Rf temp
        done
      env:
        DOWNLOAD_PATH: ${{ steps.download.outputs.download-path }}
