on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'frontends/**'
      - 'utils/**'
      - '**/*.md'
      - 'compose/**'
      - 'dev-env/**'
      - 'api/**'
    branches:
      - main

name: main - release - java 17
jobs:
  build:
    name: Releasing branch - main
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
#          - linux/arm64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.ref }}
        fetch-depth: 0

    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        gpg-private-key: ${{ secrets.DIALOB_GPG_KEY }}
        gpg-passphrase: DIALOB_GPG_SEC
        server-id: oss.sonatype.org
        server-username: OSSRH_USER
        server-password: OSSRH_PASS

    - name: Docker Hub login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: tag - release - upload
      run: ./dialob-build-parent/release.sh
      env:
        BOT_NAME: "info"
        BOT_EMAIL: "info@dialob.io"
        DOCKER_REGISTRY: docker.io/resys
        DIALOB_GPG_SEC: ${{ secrets.DIALOB_GPG_SEC }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        OSSRH_PASS: ${{ secrets.OSSRH_PASS }}

    - name: upload image metadata
      uses: actions/upload-artifact@v4
      with:
        name: jib-image
        path: '**/target/jib-image.*'
