on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'utils/**'
      - '**/*.md'
      - 'compose/**'
      - 'dev-env/**'
    branches:
      - dev
      - dev-*

name: pull request - build

jobs:
  build:
    name: Build - pull request
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build
        run: ./mvnw -B -Dmaven.javadoc.skip=false -Dsonar.projectKey=dialob_dialob-parent verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
