on:
  push:
    branches:
      - digiexpress

name: 3.x - release - java 11
jobs:
  build:
    name: Releasing branch - digiexpress - version 3.x
    if: "contains(github.event.head_commit.message, 'make-release-3.x')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        ref: digiexpress

    - uses: joschi/setup-jdk@v2
      with:
        java-version: '11'

    - name: digiexpress - 3.x - tag - release - upload
      run: ./dialob-build-parent/release.sh
      env:
        CI: false
        BOT_NAME: "info"
        BOT_EMAIL: "info@dialob.io"
        GITHUB_SHA: ${GITHUB_SHA}
        GITHUB_REF: ${GITHUB_REF}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        GPG_KEY_ID: ${{ secrets.DIALOB_GPG_KEY_ID }}
        GPG_KEY: ${{ secrets.DIALOB_GPG_KEY }}
        GPG_KEY_SEC:  ${{ secrets.DIALOB_GPG_SEC }}
        OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        
        
